name: NupChat iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: ðŸŽ‰ iOS Build
    runs-on: macos-latest

    defaults:
      run:
        working-directory: nupchatflutter

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Flutter pub get
        run: flutter pub get

      - name: Update CocoaPods
        run: pod repo update
        working-directory: nupchatflutter/ios

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Create Payload
        run: mkdir Payload
        working-directory: nupchatflutter/build/ios/iphoneos

      - name: Move Runner.app
        run: mv Runner.app Payload
        working-directory: nupchatflutter/build/ios/iphoneos

      - name: Zip IPA
        run: zip -qq -r -9 NupChat.ipa Payload
        working-directory: nupchatflutter/build/ios/iphoneos

      - name: Upload IPA to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: nupchatflutter/build/ios/iphoneos/NupChat.ipa
          tag: v1.0
          overwrite: true
          body: "iOS build from nupchatflutter"
